### PR TITLE
Sh/media search how to guide

### PR DESCRIPTION
**Pull request by simon-dev-ml**
https://gitlab.com/silverpond/products/highlighter_all/-/issues/950

### CODE REVIEW

**Comment by jonochang** [comment]
I suggest following how Cloudflare approaches documenting common tasks (ie., how-tos / task-oriented docs). See https://developers.cloudflare.com/fundamentals/basic-tasks/manage-subdomains/ or https://developers.cloudflare.com/fundamentals/basic-tasks/test-speed/ as an example.

Given it is a task, I propose starting the heading with a VERB eg., `Search Media` or `Search and Download Files`

I also suggest having a preamble to introduce the section and to break down the 3 sub-tasks so that it is easier navigate eg.,

`Once data has been uploaded and processed in Highlighter, it is common to look for files to download them or to add them to new orders for processing.  You can jump to those subtasks below:
* Search for files
* Download files found
* Add files found to a new process order
`

**Comment by simon-dev-ml** [comment]
@jonochang let me know what you think

**Comment by jonochang** [comment]
> @jonochang let me know what you think

@simon-dev-ml , can you add headers that match the links in the preamble? That way it also shows up in the quick links on the right hand side.

**Comment by simon-dev-ml** [comment]
> > @jonochang let me know what you think
> 
> @simon-dev-ml , can you add headers that match the links in the preamble? That way it also shows up in the quick links on the right hand side.

Done

**Comment by simon-dev-ml** [comment]
> > > @jonochang let me know what you think
> > 
> > 
> > @simon-dev-ml , can you add headers that match the links in the preamble? That way it also shows up in the quick links on the right hand side.
> 
> Done

Hey @jonochang , when you hav a chance let me know, I'm keen to get back to Macuject as it's been some weeks now

**Review by jonochang — APPROVED** [review]
Good to merge once we've added better navigation in the page.

**Pull request merged**
